### ISSUE TITLE
Tried to create a logout button but it doesn't work after exiting the app.

### ISSUE THREAD

**Issue by rlam3** [venmo/Static#100]
I created a Section with a Row to enable the viewcontroller to be dismissed. This works when it is a fresh login and log out.

However the problem is when I exited and quit the app and went back in to logout. It didn't trigger any actions at all. 

Currently the app has a tabviewcontroller and a navigationcontroller embeded... What could possibly tripping up with the dismiss? Thanks! 

```swift
Section(
                header: "",
                rows: [
                    Row(
                        text:"Logout",
                        selection:{

                            self.dismiss(animated: true, completion: nil)
                            
                        }
                    ),
                ]
            ),
```

**Comment by eliperkins** [comment]
> This works when it is a fresh login and log out.

I'm not sure this is enough information for us to create a helpful bug report for you. Do you have more code you can share, perhaps extracted out into a sample project, so that we can debug this more?

My first instinct is that the `self` you're referencing in your section is being deallocated on your "login and log out", or that your scoping of `self` is off. I would try creating a function that is called within `selection`, rather than including the logic directly in here.

I'm going to close this issue for now since there's not enough information here. If you have an example project you can share, feel free to reopen the issue. Thanks!

**Comment by rlam3** [comment]
@eliperkins Is there a way for me to set Row's text with a nslocalizable string?
