### ISSUE TITLE
Why do you call it Static?

### ISSUE THREAD

**Issue by onmyway133** [venmo/Static#121]
Correct me if I'm wrong, you name the repo as "Simple static table views for iOS in Swift". I read the code https://github.com/venmo/Static/blob/master/Static/DataSource.swift and it's just a very simple wrapper around `UITableViewDataSource`. It is apparently just tableview with dynamic cell recycling. 

I would expect it to behave like `UITableViewController` in Storyboard which has static cell. Which part makes it static 🤔

**Comment by eliperkins** [comment]
I'm sure @soffes can chime in with the true origin stories of the name, but I would certainly say that the true meaning of the name and the current state of the project have definitely diverged.

When Static started, it truly was for only Static table views. It was a simple declarative API for creating static rows in a `UITableView` for things like a Settings screen, where the same hardcoded data produced the same UI every time (mildly inspired a bit by React's "UI is a function of props and state"). Cells were (mostly) homogeneous, consisting mostly of an image and some text, and each pushed to its own screen. This could easily be defined as data, rather than as a set of delegate methods. By abstracting this out, we found a set of APIs that worked well for spinning up a table view really quickly without creating multiple objects or classes to maintain.

Over time, we've found that not all table views are static, even if they start this way, but we could bend the nice declarative API we created to maintain the same paradigm. So we bolted on more knobs and buttons to the API and we ended up with being able to define _data_ that created table views and cells, rather than _objects and classes_ that created table views and cells.

I think with the more knobs, buttons, bells and whistles that get added in, we lost sight of the original goal of the project, and ended up with what you see today, which is, yes, a data-driven wrapper around `UITableView`, `UITableViewDelegate`, `UITableViewDataSource` and `UITableViewController`. Whether or not this project is truly "static", in the programming language sense of the term, I think has little meaning as to what this project actually provides to its users. I wouldn't mind seeing the description of the repo change, but there's no sense in changing the name.

I'd love to see others chime in here!

**Comment by onmyway133** [comment]
@eliperkins Thanks, I get it. I think this is a nice abstraction

**Comment by soffes** [comment]
Exactly, @eliperkins. @onmyway133 here's my blog post from when it was created: https://soffes.blog/static

The goal of static was to make creating a bunch of cells easy without a bunch of switch statements in cell for row, did select, etc.

```swift
Section(header: "Money", rows: [
    Row(text: "Balance", detailText: "$12.00", accessory: .disclosureIndicator, selection: {
        // Show statement
    }),
    Row(text: "Transfer to Bank…", cellClass: ButtonCell.self, selection: {
        // Show transfer to bank modal
    })
], footer: "Transfers usually arrive within 1-3 business days.")
```

That would be a ton of code if you were to do it in the conventional way. At Venmo when we created this, we weren't using IB and this solved a need we had. The goal was never to make something that worked in IB, since the provided functionality is great if you want to use IB.

Totally understand if this isn't what you were looking for :)

Feel free to comment if you have more questions!
