### ISSUE TITLE
Fatal Bug!!!

### ISSUE THREAD

**Issue by change2hao** [venmo/Static#139]
in the demo, when I put more than one 
`Row(text: "Custom View", accessory: .view(customAccessory), accessibilityIdentifier: "CustomView")`
the app will pending forever

**Comment by eliperkins** [comment]
I'm not sure what you mean about "pending forever." Can you share some more code to reproduce this?

**Comment by dmiluski** [comment]
Hi @change2hao :

 I just ran the example app locally, and by adding a copy of the CustomView row you mention above just after the existing one I also see an app appear to freeze upon scrolling to reveal the duplicated row which was off screen.

It turns out the hang is the attempt to include the same instance of a view in two separate cell accessories:
https://github.com/venmo/Static/blob/f8867ece36da0b471e027286c96118986b9b1375/Example/ViewController.swift#L8

Given this is an example app, and a user can avoid this by not duplicating a row's accessory with the use of a factory to provide view instances, marking this issue closed.
