### ISSUE TITLE
`tableView:cellForRowAtIndexPath` not called

### ISSUE THREAD

**Issue by mokagio** [venmo/Static#27]
Hello, I really like this library. Solves a known problem in a really tidy way, kudos.

I was just having a play around when I found what might be an issue... My usual setup for table views is a `UIViewController` to which a `UITableView` is added, either via IB or code. The reason for that is that I prefer having full control on the view, rather than relying on `UITableViewController`.

The code using Static would look like this:

```swift
import UIKit
import Static

class ViewController: UIViewController, UITableViewDataSource {

    @IBOutlet var tableView: UITableView!

    override func viewDidLoad() {
        super.viewDidLoad()


        let _ = DataSource(tableView: tableView, sections: [
            Section(rows: [
                Row(text: "Hello I'm a Row")
                ])
            ])
    }
}
```

It looks pretty simple right? Well when I'm running the row(s) are not shown.

I pulled the Static source and put some breakpoints and what I found is that `numberOfSectionsInTableView` and `tableView:numberOfRowsInSection:` are called, and give the expected result, but `tableView:cellForRowAtIndexPath:` isn't. I found that quite baffling 😳

I made a quick [example project](https://github.com/mokagio/Static-Example) to reproduce the issue. Note, I'm running Xcode 7 Beta 4.

Cheers :beers:

**Comment by hyperspacemark** [comment]
Short answer: You need to retain your instance of `DataSource`.

Long answer: The initializer for `DataSource` will assign itself to `tableView.dataSource`, but that is a weak property and without another object retaining ownership, it will be deallocated. In your example, the instance of `DataSource` you're creating will be deallocated at the end of `viewDidLoad()`.

It's surprising that you saw `numberOfSectionsInTableView(tableView:)` and `tableView(tableView: numberOfRowsInSection:)` invoked but my purely speculative theory is that, when assigning a value to the `dataSource` property on an instance of `UITableView`, the table view will immediately consult the data source about the number of sections and rows for internal bookkeeping reasons. I bet that the data source was _not_ consulted for any cells because, since the view controller had not yet been presented, the view controller's view (and subsequently the table view) had not yet been laid out and `tableView` still has a zero rect. In this case, it would be inefficient for the table view to start asking for cells when it does not yet know how many would be needed to fill its bounds.

**Comment by mokagio** [comment]
> You need to retain your instance of `DataSource`.

![](https://pbs.twimg.com/profile_images/3483499580/01e5c771e94e14708c5f2638f14a0d77.png)

Yep, that makes absolute sense! Derp.

Thanks heaps :beers:

**Comment by soffes** [comment]
Great explaination @hyperspacemark :)
