### ISSUE TITLE
Animations when adding cells to data source?

### ISSUE THREAD

**Issue by kermankohli** [venmo/Static#59]
It'd be really useful if there could be animations for when cells are added to the data source through: self.dataSource.sections[0].rows.insert

Particularly useful for date pickers and drop down inputs:)

**Comment by eliperkins** [comment]
@kermankohli for sure! This would definitely be an awesome API, but I would place it out of scope of what Static is trying to accomplish, which is simply to provide a value-typed data layer to table views.

I would love to see an approach towards an API like this as an extension of the project, rather than one baked in by default! Keep me posted on if you can come up with a way to accomplish this. :)
