### ISSUE TITLE
Swift 3.0

### ISSUE THREAD

**Issue by chrismanderson** [venmo/Static#83]
Would love to see this working with Swift 3/Xcode 8! Happen to have a rough idea of if/when that might happen?

**Comment by eliperkins** [comment]
I think we summed up our Swift 3 migration strategy in #84!

**Comment by eliperkins** [comment]
Reopening this issue as the GM was released yesterday! 🎉 

One thing I would like to support, moving forward, is still maintaining a version with Swift 2.3 support, theoretically `v1.2.0`. Then, we should be able to migrate to Swift 3 and name the version `v2.0.0`.

I think libraries like [thoughtbot/Argo do an awesome job of this](https://github.com/thoughtbot/Argo#version-compatibility) using a "Version Compatibility" table to show all of this off.

What do y'all think, @soffes, @hyperspacemark, @chrismanderson?

**Comment by eliperkins** [comment]
Additionally, the `swift-23` branch needs no changes to run on Xcode 8 GM with Swift 2.3.

**Comment by soffes** [comment]
@eliperkins I have full Swift 3 support in my fork. Happy to PR.

If it were solely up to me, I'd skip 2.3 and just do 3.0 with a minor (or major?) version bump.

**Comment by eliperkins** [comment]
Yeah, I don't mind going right to Swift 3.0 moving forward, but it'd be nice to point to a tag for Swift 2.3 people (us included 😬 ) in the meantime. I think the intention of the major bump was due to  binary incompatibility if you were consuming it with Carthage and resolving to `~> 1.0`. By bumping right to `v2.0.0` with Swift 3, we can kinda get around it.

I don't feel too passionately about what version numbers we pick in the end, but I'd like to tag a version specifically for Swift 2.3.

**Comment by hyperspacemark** [comment]
I'm in favor of a major version bump for Swift 3 because we're not where ready to upgrade and still selfishly need a tag for Swift 2.3

**Comment by eliperkins** [comment]
Swift 3 has landed on master! Version 2.0 bump incoming, next.
